---
## update apt packages
- name: Updating apt Packages
  become: true
  apt:
    update_cache: true

## upgrade packages
- name: Upgrading Packages
  become: true
  apt:
    upgrade: true

## install dependencies, such as NodeJS and NPM
- name: Installing Dependencies
  become: true
  apt:
    name: [nodejs, npm]
    state: latest
    update_cache: true

## install pm2
- name: Installing pm2
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present