---
## Create a backend folder in the EC2 instance
- name: Creating directory
  file:
    path: /home/ubuntu/backend
    state: directory

## Copy and extract the tar file
- name: Extracting files
  unarchive:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/backend

## Starting the app
- name: Starting the app
  shell: |
    # cd /home/ubuntu/backend
    # npm install
    # # npm run build
    # pm2 stop default
    # pm2 start npm -- start
    pm2 start -f /home/ubuntu/backend/dist/main.js
